apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagp-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: nagp-api-service
  template: 
    metadata: 
      name: nagp-api-service
      labels: 
        app: nagp-api-service
    spec: 
      containers:
      - name: nagp-api-service
        image: siriabhi/nagp-api-image:6
        ports: 
        - containerPort: 3010
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        envFrom:
        - secretRef: 
            name: nagp-api-secret
        - configMapRef:
            name: nagp-api-config
           
